" let g:molokai_original = 1
" let g:rehash256 = 1

" enable mouse support
set mouse=a

" enable syntax
syntax on

" enable line numbers
set number
set relativenumber

" highlight current line
set cursorline
:highlight Cursorline cterm=bold ctermfg=yellow ctermbg=black

" enable highlight search pattern
set hlsearch

" enable smartcase search sensitivity
set ignorecase
set smartcase

" Indentation using spaces
" tabstop:     width of tab character
" softtabstop: fine tunes the amount of whitespace to be added
" shiftwidth:  determines the amount of whitespace to add in normal mode
" expandtab:   when one use space instead of tab
" textwidth:   text wrap width
" auto indent: autoindent in new line
set tabstop     =4
set softtabstop =4
set shiftwidth  =4
set textwidth   =79
set noexpandtab
set autoindent

set backspace=2

" show the matching part of the pairs [] {} and ()
set showmatch

" remove trailing whitespace from Python and Fortran files
autocmd BufWritePre *.py :%s/\s\+$//e
autocmd BufWritePre *.f90 :%s/\s\+$//e
autocmd BufWritePre *.f95 :%s/\s\+$//e
autocmd BufWritePre *.for :%s/\s\+$//e

set t_Co=256

" enable true colors support
set termguicolors

" dracula color theme: https://github.com/dracula/vim/tree/master
if v:version < 802
	packadd! dracula
endif
colorscheme dracula

set background=dark
set laststatus=2
